from setuptools import setup, Extension
from Cython.Build import cythonize

extensions = [
    Extension(
        "lte_sim_wrapper",  # The name of your Cython extension
        sources=[
            'lte_sim_wrapper.pyx', 'lte-sim-dev/src/LTE-Sim.cpp',
            'lte-sim-dev/src/componentManagers/NetworkManager.cpp',
            'lte-sim-dev/src/componentManagers/FrameManager.cpp',
            'lte-sim-dev/src/componentManagers/FlowsManager.cpp',
            'lte-sim-dev/src/core/cartesianCoodrdinates/CartesianCoordinates.cpp',
            'lte-sim-dev/src/core/idealMessages/ideal-control-messages.cc',
            'lte-sim-dev/src/core/eventScheduler/simulator.cc', 'lte-sim-dev/src/core/eventScheduler/calendar.cpp',
            'lte-sim-dev/src/core/eventScheduler/event.cpp', 'lte-sim-dev/src/core/spectrum/bandwidth-manager.cpp',
            'lte-sim-dev/src/core/spectrum/transmitted-signal.cpp', 'lte-sim-dev/src/phy/lte-phy.cpp',
            'lte-sim-dev/src/phy/simple-error-model.cpp', 'lte-sim-dev/src/phy/ue-lte-phy.cpp',
            'lte-sim-dev/src/phy/interference.cpp', 'lte-sim-dev/src/phy/henb-lte-phy.cpp',
            'lte-sim-dev/src/phy/error-model.cpp', 'lte-sim-dev/src/phy/enb-lte-phy.cpp',
            'lte-sim-dev/src/phy/wideband-cqi-eesm-error-model.cpp', 'lte-sim-dev/src/channel/LteChannel.cpp',
            'lte-sim-dev/src/channel/propagation-model/propagation-loss-model.cpp',
            'lte-sim-dev/src/channel/propagation-model/microcell-area-channel-realization.cpp',
            'lte-sim-dev/src/channel/propagation-model/3gpp-downlin-channel-realization.cpp',
            'lte-sim-dev/src/channel/propagation-model/macrocell-urban-area-channel-realization.cpp',
            'lte-sim-dev/src/channel/propagation-model/macrocell-rural-area-channel-realization.cpp',
            'lte-sim-dev/src/channel/propagation-model/channel-realization.cpp',
            'lte-sim-dev/src/channel/propagation-model/winner-downlink-channel-realization.cpp',
            'lte-sim-dev/src/channel/propagation-model/femtocell-urban-area-channel-realization.cpp',
            'lte-sim-dev/src/channel/propagation-model/macrocell-sub-urban-area-channel-realization.cpp',
            'lte-sim-dev/src/protocolStack/protocol-stack.cpp', 'lte-sim-dev/src/protocolStack/rrc/rrc-entity.cc',
            'lte-sim-dev/src/protocolStack/rrc/ho/ho-manager.cpp',
            'lte-sim-dev/src/protocolStack/rrc/ho/handover-entity.cpp',
            'lte-sim-dev/src/protocolStack/rrc/ho/power-based-ho-manager.cpp',
            'lte-sim-dev/src/protocolStack/rrc/ho/position-based-ho-manager.cpp',
            'lte-sim-dev/src/protocolStack/nas/nas-entity.cpp',
            'lte-sim-dev/src/protocolStack/mac/enb-mac-entity.cc',
            'lte-sim-dev/src/protocolStack/mac/harq-manager.cpp',
            'lte-sim-dev/src/protocolStack/mac/ue-mac-entity.cc',
            'lte-sim-dev/src/protocolStack/mac/AMCModule.cpp', 'lte-sim-dev/src/protocolStack/mac/mac-entity.cc',
            'lte-sim-dev/src/protocolStack/mac/henb-mac-entity.cpp',
            'lte-sim-dev/src/protocolStack/mac/packet-scheduler/mt-uplink-packet-scheduler.cpp',
            'lte-sim-dev/src/protocolStack/mac/packet-scheduler/exp-rule-downlink-packet-scheduler.cpp',
            'lte-sim-dev/src/protocolStack/mac/packet-scheduler/dl-mlwdf-packet-scheduler.cpp',
            'lte-sim-dev/src/protocolStack/mac/packet-scheduler/mw-rule-downlink-packet-scheduler.cpp',
            'lte-sim-dev/src/protocolStack/mac/packet-scheduler/packet-scheduler.cpp',
            'lte-sim-dev/src/protocolStack/mac/packet-scheduler/dl-pf-packet-scheduler.cpp',
            'lte-sim-dev/src/protocolStack/mac/packet-scheduler/dl-exp-packet-scheduler.cpp',
            'lte-sim-dev/src/protocolStack/mac/packet-scheduler/dl-fls-packet-scheduler.cpp',
            'lte-sim-dev/src/protocolStack/mac/packet-scheduler/log-rule-downlink-packet-scheduler.cpp',
            'lte-sim-dev/src/protocolStack/mac/packet-scheduler/enhanced-uplink-packet-scheduler.cpp',
            'lte-sim-dev/src/protocolStack/mac/packet-scheduler/downlink-packet-scheduler.cpp',
            'lte-sim-dev/src/protocolStack/mac/packet-scheduler/uplink-packet-scheduler.cpp',
            'lte-sim-dev/src/protocolStack/mac/packet-scheduler/roundrobin-uplink-packet-scheduler.cpp',
            'lte-sim-dev/src/protocolStack/mac/packet-scheduler/delay-edd-rule-downlink-packet-scheduler.cpp',
            'lte-sim-dev/src/protocolStack/rlc/amd-record.cpp',
            'lte-sim-dev/src/protocolStack/rlc/um-rlc-entity.cpp',
            'lte-sim-dev/src/protocolStack/rlc/tm-rlc-entity.cpp',
            'lte-sim-dev/src/protocolStack/rlc/am-rlc-entity.cpp',
            'lte-sim-dev/src/protocolStack/rlc/rlc-entity.cc',
            'lte-sim-dev/src/protocolStack/rlc/am-state-variables.cpp',
            'lte-sim-dev/src/protocolStack/pdcp/pdcp-entity.cpp',
            'lte-sim-dev/src/protocolStack/packet/Header.cpp',
            'lte-sim-dev/src/protocolStack/packet/packet-burst.cc',
            'lte-sim-dev/src/protocolStack/packet/PacketTAGs.cpp',
            'lte-sim-dev/src/protocolStack/packet/Packet.cpp',
            'lte-sim-dev/src/protocolStack/protocols/TransportProtocol.cpp',
            'lte-sim-dev/src/mobility/ConstantPosition.cpp', 'lte-sim-dev/src/mobility/Mobility.cpp',
            'lte-sim-dev/src/mobility/RandomWaypoint.cpp', 'lte-sim-dev/src/mobility/Manhattan.cpp',
            'lte-sim-dev/src/mobility/RandomWalk.cpp', 'lte-sim-dev/src/mobility/RandomDirection.cpp',
            'lte-sim-dev/src/device/Gateway.cpp', 'lte-sim-dev/src/device/HeNodeB.cpp',
            'lte-sim-dev/src/device/ENodeB.cpp', 'lte-sim-dev/src/device/UserEquipment.cpp',
            'lte-sim-dev/src/device/NetworkNode.cpp', 'lte-sim-dev/src/device/CqiManager/wideband-cqi-manager.cpp',
            'lte-sim-dev/src/device/CqiManager/fullband-cqi-manager.cpp',
            'lte-sim-dev/src/device/CqiManager/cqi-manager.cpp',
            'lte-sim-dev/src/device/IPClassifier/Classifier.cpp',
            'lte-sim-dev/src/device/IPClassifier/ClassifierParameters.cpp',
            'lte-sim-dev/src/flows/radio-bearer-sink.cpp', 'lte-sim-dev/src/flows/radio-bearer.cpp',
            'lte-sim-dev/src/flows/MacQueue.cpp', 'lte-sim-dev/src/flows/radio-bearer-instance.cpp',
            'lte-sim-dev/src/flows/QoS/QoSForM_LWDF.cpp', 'lte-sim-dev/src/flows/QoS/QoSForFLS.cpp',
            'lte-sim-dev/src/flows/QoS/QoSForEXP.cpp', 'lte-sim-dev/src/flows/QoS/QoSParameters.cpp',
            'lte-sim-dev/src/flows/application/WEB.cpp', 'lte-sim-dev/src/flows/application/VoIP.cpp',
            'lte-sim-dev/src/flows/application/CBR.cpp', 'lte-sim-dev/src/flows/application/TraceBased.cpp',
            'lte-sim-dev/src/flows/application/InfiniteBuffer.cpp',
            'lte-sim-dev/src/flows/application/Application.cpp',
            'lte-sim-dev/src/flows/application/application-sink.cpp',
            'lte-sim-dev/src/networkTopology/DualStripe.cpp', 'lte-sim-dev/src/networkTopology/Building.cpp',
            'lte-sim-dev/src/networkTopology/5x5ApartmentGrid.cpp', 'lte-sim-dev/src/networkTopology/Cell.cpp',
            'lte-sim-dev/src/networkTopology/Femtocell.cpp', 'lte-sim-dev/src/networkTopology/Street.cpp'
        ],

        language="c++",
        include_dirs=[
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/componentManagers',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/core',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/core/cartesianCoodrdinates',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/core/idealMessages',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/core/eventScheduler',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/core/spectrum',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/TEST',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/phy',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/phy/BLERTrace',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/channel',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/channel/propagation-model',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/channel/propagation-model/FastFadingRealization',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/channel/propagation-model/FastFadingRealization/zheng_model',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/channel/propagation-model/FastFadingRealization/make_fast_fading',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/channel/propagation-model/FastFadingRealization/jakes_model',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/protocolStack',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/protocolStack/rrc',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/protocolStack/rrc/ho',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/protocolStack/nas',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/protocolStack/mac',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/protocolStack/mac/packet-scheduler',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/protocolStack/rlc',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/protocolStack/pdcp',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/protocolStack/packet',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/protocolStack/protocols',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/mobility',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/scenarios',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/device',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/device/CqiManager',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/device/IPClassifier',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/flows',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/flows/QoS',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/flows/application',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/flows/application/Trace',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/networkTopology',
            '/Users/atherashraf/PycharmProjects/PhDStudents/py-lte-sim-dev/lte-sim-dev/src/utility'
        ],
        extra_compile_args=["-std=c++11", "-arch", "arm64", "-undefined", "dynamic_lookup"],  # Compile for ARM64
        extra_link_args=["-arch", "arm64", "-undefined", "dynamic_lookup"],  # Link for ARM64

        libraries=["stdc++"]  # Add this to link the C++ standard library
    )
]

setup(
    ext_modules=cythonize(extensions),
)
